---
abstract: 'HTML trimmer'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Trim
no_index:
  directory:
    - inc
    - t
requires:
  Exporter::Lite: 0
  Filter::Util::Call: 0
  HTML::Parser: 0
  Unicode::EastAsianWidth: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
